#copied from @MAUFORONDA

name: Update data
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run script
        run: |
          echo ::set-output name=results::$(python testing.ipynb)
        id: run_script
      - name: what changed
        env:
          RESULTS: ${{ steps.run_script.outputs.results }}
        run: |
          echo ::set-output name=number::$(echo "$RESULTS" | jq ".number")
          echo ::set-output name=message::$(echo "$RESULTS" | jq ".message" | sed -e "s/\"//g")
        id: changed
      - name: log
        env:
          NUMBER: ${{ steps.changed.outputs.number }}
          MESSAGE: ${{ steps.changed.outputs.message }}
        run: |
          echo "results"
          echo "$NUMBER changes"
          echo "message: $MESSAGE"
      - name: commit
        env:
          NUMBER: ${{ steps.changed.outputs.number }}
          MESSAGE: ${{ steps.changed.outputs.message }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.changed.outputs.number > 0 
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] $MESSAGE"
          git push -q "https://$GH_TOKEN@github.com/dquintani/testing.git" master






# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
